<?xml version="1.0" encoding="utf-8"?><Database Name="PersonCars" Class="PeopleCarsDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=PersonCars;Integrated Security=True" SettingsObjectName="PeopleCars.Data.Properties.Settings" SettingsPropertyName="ConStr" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Make" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="People_Car" Member="People" ThisKey="PersonId" OtherKey="Id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.People" Member="Peoples">
    <Type Name="People">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="People_Car" Member="Cars" ThisKey="Id" OtherKey="PersonId" Type="Car" />
      <Association Name="People_People" Member="People2" ThisKey="Id" OtherKey="Id" Type="People" Cardinality="One" />
      <Association Name="People_People" Member="People1" ThisKey="Id" OtherKey="Id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
</Database>